process.on('uncaughtException', function(error){
    console.log('ocorreu um erro.');
});
